title: DOM Cloud
author:
  name: Wildan M
  email: willnode@wellosoft.net
sass:
  style: compressed
google_analytics: "UA-109180894-3"
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - Gruntfile.js
  - node_modules
  - _site
  - .jekyll-cache